[package]
name = "rust-consul"
version = "0.0.1"

[dependencies]
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
native-tls = "*"
log = "0.3"
tokio-core = "0.1"
url = "1.5"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
